apiVersion: v1
kind: Service
metadata:
  name: hello-app-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: hello-app
    
#spec:
#  ports:
#  - name: http
#    port: 8080
#    protocol: TCP
#    targetPort: 80
#  selector:
#    app: hello-app
#  type: LoadBalancer
  